### default supported ROS message types:
# sensor_msgs/Imu IMU数据
# geometry_msgs/Twist 几何信息
# std_msgs/String 字符串
### max number of send_topics supported: 70 支持的最大发送主题数：50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robota: 192.168.10.104
  robotb: 192.168.10.105
  robotc: 192.168.10.103
  PC2: 192.168.10.101


####### Send these ROS messages to remote robots #######i
## if no send_topics needed, comment all these out
send_topics:
# 小车当前位姿/a/ndt_pose
- topic_name: /ndt_pose
  msg_type: geometry_msgs/PoseStamped
  max_freq: 10
  srcIP: robota
  srcPort: 3021
# 车辆状态：电量、速度、故障状态
- topic_name: /scout_status_a
  msg_type: swarm_ros_bridge/ScoutStatus
  max_freq: 10
  srcIP: robota
  srcPort: 3022

- topic_name: /BMS_status_a
  msg_type: swarm_ros_bridge/ScoutBmsStatus
  max_freq: 10
  srcIP: robota
  srcPort: 3023


## 笔记本传来的消息
recv_topics:
## 1.启动指令
- topic_name: /start_order
  msg_type: swarm_ros_bridge/start
  srcIP: PC2
  srcPort: 3001
## 2.规划好的路径 发a小车需要走的规划路径给a小车
- topic_name: /astra_path_a
  msg_type: std_msgs/Float64MultiArray
  srcIP: PC2
  srcPort: 3002

