### default supported ROS message types:
# sensor_msgs/Imu IMU数据
# geometry_msgs/Twist 几何信息
# std_msgs/String 字符串
# (modify/add in ros_sub_pub.hpp if you need more)如果需要更多，请修改/添加 ros_sub_pub.hpp
### max number of send_topics supported: 50 支持的最大发送主题数：50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robota: 192.168.57.211
  robotb: 192.168.57.212
  robotc: 192.168.57.213
  airfly: 100.104.128.117
  PC2: 192.168.57.1
  # PC3: 127.0.0.1
  
send_topics:
##发a小车需要走的规划路径给a小车
- topic_name: /astar_path_a
  msg_type: std_msgs/Float64MultiArray
  max_freq: 50 
  srcIP: PC2 
  srcPort: 3002
##发b小车需要走的规划路径给b小车
- topic_name: /astar_path_b
  msg_type: std_msgs/Float64MultiArray
  max_freq: 50 
  srcIP: PC2 
  srcPort: 3003 

##发c小车需要走的规划路径给c小车
- topic_name: /astar_path_c
  msg_type: std_msgs/Float64MultiArray
  max_freq: 50 
  srcIP: PC2 
  srcPort: 3004 

## 发送给a、b、c车的栅格地图和ymal文件
- topic_name: /pgm_image
  msg_type: sensor_msgs/Image
  max_freq: 25 
  srcIP: PC2 
  srcPort: 3005 

- topic_name: /map_yaml
  msg_type: swarm_ros_bridge/yamlMsg
  max_freq: 25 
  srcIP: PC2 
  srcPort: 3006 

# 笔记本给ABC的启动指令
- topic_name: /cmd_A
  msg_type: std_msgs/Int8
  max_freq: 50
  srcIP: PC2
  srcPort: 3007

- topic_name: /cmd_B
  msg_type: std_msgs/Int8
  max_freq: 50
  srcIP: PC2
  srcPort: 3008

- topic_name: /cmd_C
  msg_type: std_msgs/Int8
  max_freq: 50
  srcIP: PC2
  srcPort: 3009

##无人机传递的地图和图像信息
##a、b、c三辆车发送的状态（电量、速度、故障状态）、当前位姿
recv_topics:
#通讯状态
- topic_name: /A_is_connected
  msg_type: std_msgs/Int64
  srcIP: robota
  srcPort: 3024

- topic_name: /B_is_connected
  msg_type: std_msgs/Int64
  srcIP: robotb
  srcPort: 3034

- topic_name: /C_is_connected
  msg_type: std_msgs/Int64
  srcIP: robotc
  srcPort: 3044

- topic_name: /airfly_is_connected
  msg_type: std_msgs/Int64
  srcIP: airfly
  srcPort: 3015

#a车发的消息 
- topic_name: /a/ndt_pose
  msg_type: geometry_msgs/PoseStamped
  srcIP: robota
  srcPort: 3021

- topic_name: /a/scout_status
  msg_type: swarm_ros_bridge/ScoutStatus
  srcIP: robota
  srcPort: 3022

- topic_name: /BMS_status_a
  msg_type: swarm_ros_bridge/ScoutBmsStatus
  srcIP: robota
  srcPort: 3023

#b车发的消息  /b/ndt_pose
- topic_name: /b/ndt_pose
  msg_type: geometry_msgs/PoseStamped
  srcIP: robotb
  srcPort: 3031

- topic_name: /b/scout_status
  msg_type: swarm_ros_bridge/ScoutStatus
  srcIP: robotb
  srcPort: 3032

- topic_name: /BMS_status_b
  msg_type: swarm_ros_bridge/ScoutBmsStatus
  srcIP: robotb
  srcPort: 3033 

#c车发来的消息
- topic_name: /c/ndt_pose
  msg_type: geometry_msgs/PoseStamped
  srcIP: robotc
  srcPort: 3041

- topic_name: /scout_status_c
  msg_type: swarm_ros_bridge/ScoutStatus
  srcIP: robotc
  srcPort: 3042

- topic_name: /BMS_status_c
  msg_type: swarm_ros_bridge/ScoutBmsStatus
  srcIP: robotc
  srcPort: 3043

#无人机消息 
# 图像信息
- topic_name: /camera/color/image_raw/compressed
  msg_type: sensor_msgs/CompressedImage
  srcIP: airfly 
  srcPort: 3014 
# 历史视觉点云话题(地图)
- topic_name: /rtabmap/mapData
  msg_type: swarm_ros_bridge/MapData
  srcIP: airfly 
  srcPort: 3013 




