### default supported ROS message types:
# sensor_msgs/Imu IMU数据
# geometry_msgs/Twist 几何信息
# std_msgs/String 字符串
# (modify/add in ros_sub_pub.hpp if you need more)如果需要更多，请修改/添加 ros_sub_pub.hpp
### max number of send_topics supported: 50 支持的最大发送主题数：50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robota: 192.168.10.102
  robotb: 192.168.10.106
  robotc: 192.168.10.105
  PC1: 192.168.10.107
  PC2: 192.168.10.100
  test_local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######i
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /PC2/chatter 
  msg_type: std_msgs/String 
  max_freq: 1000 
  srcIP: self 
  srcPort: 3020 



####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /PC2/chatter_recv 
  msg_type: std_msgs/String 
  srcIP: PC2 
  srcPort: 3020 

#a车：发送global_descriptor 和 /a/distributedMapping/neighborPoseEstimates
- topic_name: /a/distributedMapping/globalDescriptors
  msg_type: swarm_ros_bridge/global_descriptor
  max_freq: 10
  srcIP: robota
  srcPort: 3001

- topic_name: /a/distributedMapping/neighborPoseEstimates
  msg_type: swarm_ros_bridge/neighbor_estimate
  max_freq: 10
  srcIP: robota
  srcPort: 3002


- topic_name: /a/distributedMapping/loopInfo
  msg_type: swarm_ros_bridge/loop_info
  max_freq: 10
  srcIP: robota
  srcPort: 3003

#b车发的消息  /a/distributedMapping/loopInfo
- topic_name: /b/distributedMapping/globalDescriptors
  msg_type: swarm_ros_bridge/global_descriptor
  max_freq: 10
  srcIP: robotb
  srcPort: 3004

- topic_name: /b/distributedMapping/neighborPoseEstimates
  msg_type: swarm_ros_bridge/neighbor_estimate
  max_freq: 10
  srcIP: robotb
  srcPort: 3005

- topic_name: /b/distributedMapping/loopInfo
  msg_type: swarm_ros_bridge/loop_info
  max_freq: 10
  srcIP: robotb
  srcPort: 3006

#c车发来的消息
- topic_name: /c/distributedMapping/globalDescriptors
  msg_type: swarm_ros_bridge/global_descriptor
  max_freq: 10
  srcIP: robotc
  srcPort: 3007

- topic_name: /c/distributedMapping/neighborPoseEstimates
  msg_type: swarm_ros_bridge/neighbor_estimate
  max_freq: 10
  srcIP: robotc
  srcPort: 3008

- topic_name: /c/distributedMapping/loopInfo
  msg_type: swarm_ros_bridge/loop_info
  max_freq: 10
  srcIP: robotc
  srcPort: 3009
