### default supported ROS message types:
# sensor_msgs/Imu IMU数据
# geometry_msgs/Twist 几何信息
# std_msgs/String 字符串
# (modify/add in ros_sub_pub.hpp if you need more)如果需要更多，请修改/添加 ros_sub_pub.hpp
### max number of send_topics supported: 50 支持的最大发送主题数：50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robotc: 192.168.31.211
  PC2: 192.168.31.226

####### Send these ROS messages to remote robots #######i
## if no send_topics needed, comment all these out
send_topics:
# 小车当前位姿
- topic_name: /ndt_pose
  msg_type: geometry_msgs/PoseStamped
  max_freq: 10
  srcIP: robotc
  srcPort: 3041
# 车辆状态：电量、速度、故障状态
- topic_name: /scout_status_c
  msg_type: swarm_ros_bridge/ScoutStatus
  max_freq: 10
  srcIP: robotc
  srcPort: 3042

- topic_name: /BMS_status_c
  msg_type: swarm_ros_bridge/ScoutBmsStatus
  max_freq: 10
  srcIP: robotc
  srcPort: 3043

## 笔记本传来的消息
## 1.启动指令///
## 2.规划好的路径//##发c小车需要走的规划路径给a小车
recv_topics:
## 1.启动指令
# - topic_name: /start_order
#   msg_type: swarm_ros_bridge/start
#   srcIP: PC2
#   srcPort: 3001

- topic_name: /cmd_C
  msg_type: std_msgs/Int8
  srcIP: PC2
  srcPort: 3009
## 2.规划好的路径 发a，b，c小车需要走的规划路径给a小车
- topic_name: /astar_path_a
  msg_type: std_msgs/Float64MultiArray
  srcIP: PC2
  srcPort: 3002

- topic_name: /astar_path_b
  msg_type: std_msgs/Float64MultiArray
  srcIP: PC2
  srcPort: 3003

- topic_name: /astar_path_c
  msg_type: std_msgs/Float64MultiArray
  srcIP: PC2
  srcPort: 3004

## 接收传输的png的图片和yaml文件

- topic_name: /pgm_image
  msg_type: sensor_msgs/Image
  srcIP: PC2
  srcPort: 3005

- topic_name: /map_yaml
  msg_type: swarm_ros_bridge/yamlMsg
  srcIP: PC2
  srcPort: 3006

# ##测试使用台式机
# - topic_name: /pgm_image
#   msg_type: sensor_msgs/Image
#   srcIP: PCstatic
#   srcPort: 3005

# - topic_name: /map_yaml
#   msg_type: swarm_ros_bridge/yamlMsg
#   srcIP: PCstatic
#   srcPort: 3006