### default supported ROS message types:
# sensor_msgs/Imu IMU数据
# geometry_msgs/Twist 几何信息
# std_msgs/String 字符串
# (modify/add in ros_sub_pub.hpp if you need more)如果需要更多，请修改/添加 ros_sub_pub.hpp
### max number of send_topics supported: 50 支持的最大发送主题数：50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robota: 192.168.10.101
  robotb: 192.168.10.105
  robotc: 192.168.10.103
  airfly: 192.168.10.108
  PC2: 192.168.10.100

####### Send these ROS messages to remote robots #######i
## if no send_topics needed, comment all these out
send_topics:
##笔记本转化的栅格地图（给a,b,c）

##笔记本给小车的启动指令
- topic_name: /start_order
  msg_type: swarm_ros_bridge/start
  max_freq: 1000 
  srcIP: PC2 
  srcPort: 3050 
##发a小车需要走的规划路径给a小车

- topic_name: /a/path(待定)
  msg_type: nav_msgs/Path
  max_freq: 1000 
  srcIP: PC2 
  srcPort: 3050 
##发b小车需要走的规划路径给b小车
- topic_name: /b/path(待定)
  msg_type: nav_msgs/Path
  max_freq: 1000 
  srcIP: PC2 
  srcPort: 3050 
##发c小车需要走的规划路径给c小车
- topic_name: /c/path(待定)
  msg_type: nav_msgs/Path
  max_freq: 1000 
  srcIP: PC2 
  srcPort: 3050 



##无人机传递的地图和图像信息
##a、b、c三辆车发送的状态（电量、速度、故障状态）、当前位姿
recv_topics:
#a车发的消息  /a/distributedMapping/loopInfo
- topic_name: /a/ndt_pose
  msg_type: geometry_msg/PoseStamped
  srcIP: robotc
  srcPort: 3050

- topic_name: /a/scout_status
  msg_type: scout_msgs/ScoutStatus
  srcIP: robota
  srcPort: 3051


#b车发的消息  /a/distributedMapping/loopInfo
- topic_name: /b/ndt_pose
  msg_type: geometry_msg/PoseStamped
  srcIP: robotb
  srcPort: 3060

- topic_name: /b/scout_status
  msg_type: scout_msgs/ScoutStatus
  srcIP: robotb
  srcPort: 3061
  

#c车发来的消息
- topic_name: /c/ndt_pose
  msg_type: geometry_msg/PoseStamped
  srcIP: robotc
  srcPort: 3070

- topic_name: /b/scout_status
  msg_type: scout_msgs/ScoutStatus
  srcIP: robotb
  srcPort: 3071

#无人机消息 
# 栅格地图
- topic_name: /OccupancyGrid（待定）
  msg_type: nav_msgs/OccupancyGrid
  srcIP: airfly
  srcPort: 3040
# 带点云双目图像话题
- topic_name: /vins_fusion/image_track
  msg_type: sensor_msgs/Image
  srcIP: airfly 
  srcPort: 3041 
# 历史视觉点云话题(地图)
- topic_name: /vins_fusion/margin_cloud
  msg_type: sensor_msgs/PointCloud
  srcIP: airfly 
  srcPort: 3042 




